### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'

### ISSUE THREAD

**Issue by nice1999my** [Miraculix200/StableDiffusionUI_SageMakerSL#9]
I am getting error ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'

Please advise.

Traceback (most recent call last):
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/launch.py", line 39, in <module>
    main()
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/launch.py", line 35, in main
    start()
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/modules/launch_utils.py", line 390, in start
    import webui
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/webui.py", line 54, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/modules/call_queue.py", line 6, in <module>
    from modules import shared, progress, errors
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/modules/shared.py", line 21, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 20, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'

**Comment by daniloedu** [comment]
It seems that the notebook is not compatible anymore with SagaMaker StudioLab.

**Comment by Seremegu** [comment]
Try executing these commands in a cell:
```
!pip install pytorch-lightning==1.6.5
!pip install lightning-utilities==0.4.0
```
